#!/bin/sh

BASE_DIR="$(dirname $(realpath "$0"))"
SHELL_SCRIPT="$BASE_DIR/build/install/elph/bin/elph"
SDK_MAN_INIT="$HOME"/.sdkman/bin/sdkman-init.sh

cd "$BASE_DIR"

# If sdkman is installed, initialize the environment
[ ! -f  "$SDK_MAN_INIT" ] || { . "$SDK_MAN_INIT" && sdk env > /dev/null; }

# If the source is newer than the generated script, re-build using gradle
[ -z "$(find src -type f -newer "$SHELL_SCRIPT" 2>&1)" ] || ./gradlew clean install 1>&2

"$SHELL_SCRIPT" "$@"