#!/bin/sh

# Copyright (c) 2023 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     IBM Corporation - initial API and implementation

BASE_DIR="$(dirname $(realpath "$0"))"
SHELL_SCRIPT="$BASE_DIR/build/install/elph/bin/elph"
SDK_MAN_INIT="$HOME"/.sdkman/bin/sdkman-init.sh

cd "$BASE_DIR"

# If sdkman is installed, initialize the environment
[ ! -f  "$SDK_MAN_INIT" ] || { . "$SDK_MAN_INIT" && sdk env > /dev/null; }

# If the source is newer than the generated script, re-build using gradle
[ -z "$(find src -type f -newer "$SHELL_SCRIPT" 2>&1)" ] || ./gradlew clean install 1>&2

"$SHELL_SCRIPT" "$@"